if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  const originalMeasure = performance.measure;
  performance.measure = function (
    this: Performance,
    measureName: string,
    startOrMeasureOptions?: string | PerformanceMeasureOptions,
    endMark?: string
  ): PerformanceMeasure {
    try {
      return originalMeasure.call(this, measureName, startOrMeasureOptions, endMark);
    } catch (e) {
      return null as unknown as PerformanceMeasure;
    }
  } as typeof performance.measure;
}

import type { Metadata } from "next";
import { Geist_Mono, Geist, Tiro_Bangla } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bangla = Tiro_Bangla({
  weight: "400",
  subsets: ["bengali", "latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body
        className={`${bangla.className} antialiased`}
      >
        <QueryProvider>
          {children}
        </QueryProvider>

      </body>


    </html>
  );
}
